const items = [
  {
    id: '001',
    images: ['../images/1/1.png', '../images/1/1b.png',],
    company: 'Classic',
    item_name: 'Elegant Gold-Toned Jhumkas',
    original_price: 550,
    current_price: 450,
    discount_percentage: 22,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: { stars: 4.5, count: 1400 },
    stock: 1,
  description: 'These are a stunning pair of traditional gold-toned Jhumka earrings. They feature an intricate circular, filigree upper design from which a bell-shaped jhumka dangles. The earrings are beautifully accented with multiple strands of light green/mint green crystal beads, adding a vibrant touch of color and movement. Perfect for ethnic wear, festive occasions, or weddings.',
  },
  {
    id: '002',
    images: ['../images/2/2.jpg', '../images/2/2b.png',],
    company: 'Classic',
    item_name: 'Striking Red & Gold Dangle Earrings',
    original_price: 450,
    current_price: 350,
    discount_percentage: 22,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: { stars: 4.3, count: 24 },
    stock: 1,
    
   description: 'A sophisticated pair of gold-toned chandelier earrings featuring an ornate, round filigree drop design. The earrings are fastened with a square stud detailed with deep red crystal stones. The lower edge is elegantly embellished with five small dangling red crystal beads, providing a rich, striking contrast to the gold tone. They are an ideal accessory for special occasions and festive attire.',
  },
  {
    id: '003',
    images: ['../images/3/3.png', '../images/3/3b.png', '../images/3/3c.png',],
    company: 'Classic',
    item_name: 'Traditional Jhumkas with Ear Chains (Sahara)',
    original_price: 800,
    current_price: 599,
    discount_percentage: 25,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: { stars: 4.1, count: 249 },
    description: 'An exquisite set of traditional gold-toned Jhumka earrings complete with elegant attached pearl ear chains (Sahara/Saharay). The main earring features a circular top and a bell-shaped drop, heavily embellished with delicate white faux pearls. The long, delicate gold chain is also adorned with small clusters of pearls, designed to be worn over the ear and clipped into the hair, offering a complete, regal look. Perfect for bridal or grand occasion wear.',
    stock: 1
  },
  {
    id: '004',
    images: ['../images/4/4.png', '../images/4/4b.png', '../images/4/4c.png', '../images/4/4d.png',],
    company: 'Classic',
    item_name: 'Elegant Gold-Plated Jhumka Earrings',
    original_price: 550,
    current_price: 400,
    discount_percentage: 27,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: { stars: 5.0, count: 10 },
    sizes: [7,8],
    stock: 3,
    description: 'These exquisite gold-plated Jhumka earrings blend traditional Indian craftsmanship with a touch of modern elegance, perfect for any special occasion.',
  },
  {
    id: '005',
    images: ['../images/5/5.png', '../images/5/5b.png', '../images/5/5c.png',],
    company: 'Classic',
    item_name: 'Artisan Filigree Drop Earrings',
    original_price: 499,
    current_price: 350,
    discount_percentage: 30,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: { stars: 4.2, count: 3500 },
    sizes: [8,9],
    stock: 3,
    description: 'These exquisite gold-tone, circular drop earrings feature intricate Jaali (filigree) work, offering a sophisticated blend of traditional craftsmanship and modern appeal.',
  },
  {
    id: '006',
    images: ['images/6/6.jpeg', 'images/6/6b.jpeg', 'images/6/6c.jpeg'],
    company: 'Nike',
    item_name: 'Men ReactX Running Shoes',
    original_price: 14995,
    current_price: 14995,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: { stars: 0.0, count: 0 },
    sizes: [2,3],
    stock: 0
  },
  {
    id: '007',
    images: ['images/7/7.jpeg', 'images/7/7b.jpeg', 'images/7/7c.jpeg'],
    company: 'Classic',
    item_name: 'Men Slim Fit Regular Shorts',
    original_price: 1599,
    current_price: 639,
    discount_percentage: 60,
    rating: { stars: 4.2, count: 388 },
    sizes: [4,7],
    stock: 0
  },
  {
    id: '008',
    images: ['images/8/8.webp', 'images/8/8b.webp', 'images/8/8c.webp', 'images/8/8d.webp', 'images/8/8e.webp'],
    company: 'Classic',
    item_name: 'Adjustable Cubic Zirconia Flower Decor Bracelet for Women & Girls',
    original_price: 285,
    current_price: 142,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: { stars: 4.2, count: 5200 },
    sizes: [4,7],
    stock: 0
  }
];
